# Generated by Django 4.2.3 on 2023-07-17 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('confirmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiators', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Совпадение',
                'verbose_name_plural': 'Совпадения',
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('initiator', 'confirmer'), name='unique_initiator_confirmer'),
        ),
    ]
